### ISSUE TITLE
Add support for composed component via HoC

### ISSUE THREAD

**Issue by MoOx** [sapegin/react-styleguidist#143] opened 2016-05-09 07:21 UTC
[HoC is a good pattern](https://medium.com/@bloodyowl/the-provider-and-higher-order-component-patterns-with-react-d16ab2d1636) but when I use it, component are not recognized as such.

```js
import Wrapper from "./Wrapper"

const SidebarItem = (props) => {
  return (
    // ...
  )
})

export default Wrapper(SidebarItem)
```

Any idea how can we add support for this?
I tried to add `export { SidebarItem }` but no luck :/

**Comment by sapegin** [comment] 2016-05-09 08:35
`resolver` and `handlers` options might help here but I’ve never used them myself.

**Comment by tizmagik** [comment] 2016-05-23 19:28
I'm looking into this right now. It's a real problem with `@connect()` wrapped components with `react-redux` for example.

Ideally we shouldn't need to `export {unwrappedComponent}` but I'll try to think of ways around this. Maybe we can define some mocks to use for those wrappers or something when running in the styleguide?

Any ideas would be helpful!

**Comment by idris** [comment] 2016-06-30 20:14
Also wondering about this as many of our components are wrapped with `Relay.createContainer`

**Comment by rewmike** [comment] 2016-07-25 18:47
Has anyone tried this using the `resolver` option?

**Comment by benknight** [comment] 2016-07-26 17:30
Yeah as HoCs become a popular pattern this is definitely a serious limitation.

**Comment by sapegin** [comment] 2016-07-27 11:27
Any other ideas than export a component with some special name?

**Comment by benknight** [comment] 2016-07-27 16:51
My temporary solution is having a directory structure like this:

```
my-component
- my-component.jsx
- index.js
```

Where index.js serves as the entry point and the HoC wrapping happens there, thus leaving my-component.jsx unwrapped, and using that in the styleguide instead and manually passing it whatever props the HoC provided.

**Comment by tizmagik** [comment] 2016-07-27 18:01
I was able to do this on my project, although, it wasn't too pretty. I'm thinking about a way we can support HoC generically in `react-styleguidist` -- any insight/help would be appreciated!

But anyway, here's what I did. I hope it's helpful to some. Using the following, I was able to render an `@connect()` (redux connected) component --  although it was a very basic component with minimal other dependencies.

Use the `handlers` option defined like so (I think this mostly comes directly from the docs in this project):

```js
    handlers: docgen.defaultHandlers.concat(function (documentation, docPath) {
        // Calculate a display name for components based upon the declared class name.
        if (docPath.value.type === 'ClassDeclaration' && docPath.value.id.type === 'Identifier') {
            documentation.set('displayName', docPath.value.id.name);

            // Calculate the key required to find the component in the module exports
            if (docPath.parentPath.value.type === 'ExportNamedDeclaration') {
                documentation.set('path', docPath.value.id.name);
            }
        }

        // The component is the default export
        if (docPath.parentPath.value.type === 'ExportDefaultDeclaration') {
            documentation.set('docPath', 'default');
        }
    }),
```

I then used webpack.resolve.alias to define a mock for redux (specifically for `@connect()`), like so:

```js
updateWebpackConfig: webpackConfig => {
  webpackConfig.resolve = Object.assign(webpackConfig.resolve, appConfig.resolve);

  // Mock @connect() components
  webpackConfig.resolve.alias['react-redux'] = path.join(__dirname, '/src/util/mockRedux.js');
 
  // ... other stuff ...

  return webpackConfig;
}
```

And then mockRedux.js is very simple:

```js
export const connect = () => c => c;
```

This mostly works, but it's not ideal, but throwing it out there in case it sparks some more ideas on how to solve this cleanly in this project.

**Comment by rewmike** [comment] 2016-07-28 14:54
The "quick fix" in my project was to use a broader resolver, however it has resulted in some console errors being reported in the browser (it's finding duplicate definitions). I've made a note to look into it later (but hoping the issue is resolved sooner).

```js
resolver: require('react-docgen').resolver.findAllComponentDefinitions
```

**Comment by nhavar** [comment] 2016-09-15 20:51
I noticed that react-docgen has a pull request recently to add an HOC resolver in the mix. https://github.com/reactjs/react-docgen/pull/124

**Comment by tizmagik** [comment] 2016-09-15 21:13
@nhavar yea I noticed that too. Hopefully it gets merged soon so we can close the loop on this issue! :)

**Comment by hauptrolle** [comment] 2016-10-05 13:24
First of all thank you for your nice work. The Styleguide is awesome!

But I have a problem with a HOC wich wraps my component.
I use https://github.com/kentor/react-click-outside for my custom dropdown component, which should close on a "click-outside". But when I try to use my wrapped component in the styleguide I get the error: "Module build failed: ReferenceError: file is not defined"

I this a known problem?

Cheers!

**Comment by sapegin** [comment] 2016-10-05 13:27
@hauptrolle Most probably #179. I’d wait a few days for the new version with updated react-docgen  — it might be fixed already there.

**Comment by hauptrolle** [comment] 2016-10-05 13:40
@sapegin That would be awesome 👍  Thank you for your fast reply!

**Comment by sapegin** [comment] 2016-10-06 11:50
[4.0.0](https://github.com/sapegin/react-styleguidist/releases/tag/4.0.0) is out!

**Closed by sapegin** 2016-10-06 11:50 UTC
Labels: question

**Comment by dlim-dlim** [comment] 2017-03-16 18:28
Glad to see this thread. What is the current recommended solution to render an @connect() (redux connected) component?

When I view this component in the styleguide, I'm seeing this error:

'Invariant Violation: Could not find "store" in either the context or props of "Connect(Footer)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Footer)".'

**Comment by sapegin** [comment] 2017-03-16 18:52
Could anyone update [the cookbook](https://github.com/styleguidist/react-styleguidist/blob/next/docs/Cookbook.md)? I’m afraid I don’t have a good example.
