### ISSUE TITLE
Node API

### ISSUE THREAD

**Issue by sapegin** [sapegin/react-styleguidist#183] opened 2016-09-20 08:16 UTC
I’m working on Node API. Basically it’d be something like that:

```javascript
import { build, server, makeWebpackConfig } from 'react-styleguidist';
build({ /* full Styleguidist config */ });
build({ config: 'config file path' });
server({ /* same as above */ });
const config = makeWebpackConfig({ /* same as above */ });
```

Is that useful? Do you need anything else?

Related issues: #34, #43, #107, #162.

**Comment by sapegin** [comment] 2016-09-21 12:40
Pushed basic implementation.

@mik01aj, @operatino, @aaronjensen, @sompylasar any feedback?

**Comment by aaronjensen** [comment] 2016-09-21 13:38
This seems like a good idea just from an extensibility and design perspective. 

I don't think that it easily allows me to do what I would want in #162 or what was mentioned in the beginning of #107. 

In short, it'd be helpful to have an example of adding the styleguidist config to an existing webpack config. I don't like having to maintain two separate configs, they get out of sync easily.

**Comment by sapegin** [comment] 2016-09-21 13:39
@aaronjensen `makeWebpackConfig` should allows you to do exactly this.

**Comment by sapegin** [comment] 2016-09-21 13:45
What @mik01aj suggests in #158 should be possible with this API:

```js
// webpack.config.js
module.exports = [
    { ... user webpack config ...},
    require('react-styleguidist').makeWebpackConfig(),
];
```

**Comment by aaronjensen** [comment] 2016-09-21 13:49
@sapegin I haven't tried it yet, but I believe that would leave me with the same issues. I think that the two configs/compilers are completely separate meaning that I would still have to duplicate the loader configuration in the styleguidist config.

**Comment by sapegin** [comment] 2016-09-21 13:51
I believe you can extract them and use in both configs. I also believe that implementing some magic that will do it for you is very dangerous and isn’t the right thing to do.

**Comment by aaronjensen** [comment] 2016-09-21 13:58
I'm not suggesting magic. I'm suggesting reworking styleguidist to have as simple a setup as possible when integrating into an existing project. Something like:

1. Add the following loaders to your webpack config...
2. Add the `<Styleguide />` component somewhere in your router/render/whatever tree.

**Comment by sapegin** [comment] 2016-09-21 14:02
It’s not that simple and I think will lead to more problems than we have now. For me the more isolated Styleguidist is from user project the better. Of course you can reuse parts of you Webpack config.

**Comment by aaronjensen** [comment] 2016-09-21 14:07
Well, the problem is that it isn't all that isolated currently. It needs to build your components which means that it needs the same `module` and `resolve` configuration at a minimum in both places. In some cases it probably needs the plugin configuration as well. 

If it didn't have to build the actual components and only relied on the markdown files then yes, it could and probably should be isolated. 

When you say it's not that simple what else is there that complicates it? I'm not familiar enough w/ styleguidist to know, so pointing out the dragons would be much appreciated.

**Comment by sapegin** [comment] 2016-09-21 14:10
Mixing user project’s and Styleguidist Webpack configurations is very tricky. We’re trying to avoid it as much as possible. For example all Webpack loaders used by Styleguidist are scoped to it’s source and never affect user code.

**Comment by aaronjensen** [comment] 2016-09-21 14:15
Ah, maybe that's the issue. I remember now. Styleguidist should actually be built ahead of time as a library. This obviates any styleguidist specific configuration. Then the only configuration necessary is the loaders the user needs. This may require some changes to the extensibility points (you couldn't use alias to override components anymore) but that's ok because I'm sure we can think of better ways.

**Comment by sapegin** [comment] 2016-09-21 14:17
PR that implements it, do not break any current functionality and actually simplifies anything is very welcomed ;-)

**Comment by aaronjensen** [comment] 2016-09-21 14:17
Are you ok w/ breaking configuration changes?

**Comment by sapegin** [comment] 2016-09-21 14:18
It depends on the benefits but generally yes ;-)

**Comment by sompylasar** [comment] 2016-09-21 19:53
Thanks for pinging me here, but FWIW I'm using https://github.com/scup/atellier which provides just a React component that is reusable without extra build or configuration in existing app. It is built with webpack before being published to npm.

The only things (except UI bugs) I had to work around is make it render only on the browser-side, as I've got server-side rendering.

**Comment by sompylasar** [comment] 2016-09-21 20:12
Moreover, I've got full control over how the components are loaded and displayed on the stage.

Here's how I find all the components' styleguide descriptors located in each component's styleguide directory.

```js
import lodashUniqBy from 'lodash/uniqBy';


export default function findComponentStyleguides() {
  if ( __SERVER__ ) {
    throw new Error('Component styleguides are searched with `require.context` which is implemented in Webpack but missing from Node.');
  }

  // The directory name and the regexp aren't in variables because Webpack extracts them from the source code statically (without running it). -- sompylasar
  const styleguidesContextRequire = require.context('my-app-components', true, /^.\/[^\/]+\/styleguide\/[^\/]+$/);

  const styleguidesRelativePaths = styleguidesContextRequire.keys();

  const styleguidesInfos = styleguidesRelativePaths.map((relativePath) => {
    return {
      exports: styleguidesContextRequire(relativePath),
      relativePath,
    };
  });

  // WORKAROUND(sompylasar): For some reason, Webpack returns two references to each module, so we filter out duplicates.
  const styleguidesInfosDeduped = lodashUniqBy(styleguidesInfos, ({ exports }) => (exports));

  // Validate and filter out invalid styleguide descriptors.
  const styleguidesInfosFiltered = styleguidesInfosDeduped.filter(({ exports, relativePath }) => {
    // Validate the styleguide descriptors.
    // Require that either component or render is present.
    const isValidStyleguideDescriptor = (exports.component || exports.render);

    // Warn about invalid styleguide descriptors in the console.
    if ( !isValidStyleguideDescriptor ) {
      if (typeof console !== 'undefined' && typeof console.warn === 'function') {  // eslint-disable-line no-console
        console.warn('[Styleguide/findComponentStyleguides] ' + relativePath.replace(/^\.\//, '') + ' exports neither `component` nor `render`.');  // eslint-disable-line no-console
      }
    }

    // Keep only valid styleguide descriptors.
    return isValidStyleguideDescriptor;
  });

  // Construct the final styleguide descriptors.
  const styleguides = styleguidesInfosFiltered.map(({ exports, relativePath }) => ({
    // Flatten the `exports` object into the styleguide object.
    ...exports,
    // Add `componentPath` to the styleguide object.
    componentPath: relativePath.replace(/^\.\//, '').replace(/\/styleguide(\/(index(\.js)?)?)?$/, ''),
  }));

  return styleguides;
}
```

And here's how I render the styleguide (the declared component is rendered via React Router).

```js
import React from 'react';

import getReactComponentDisplayName from 'my-app-helpers/getReactComponentDisplayName';

import BrowserOnlyRender from 'my-app-helpers/BrowserOnlyRender';

import findComponentStyleguides from './findComponentStyleguides';


const StyleguideAtellier = () => {
  return (
    <BrowserOnlyRender>
      {() => {
        // Avoid server-side rendering because `require.context` is only available in Webpack. -- sompylasar
        const styleguides = findComponentStyleguides();

        // Require from the browser-side because `react-atellier` references `window` from the top-level module scope. -- sompylasar
        const ReactAtellier_ = require('react-atellier');
        const ReactAtellier = ( ReactAtellier_ && ReactAtellier_.__esModule ? ReactAtellier_.default : ReactAtellier_ );

        // Clear the `react-atellier` broken components list so they aren't crossed out if they've recovered from being broken. -- sompylasar
        try {
          window.localStorage.removeItem('invalidComponents');
        }
        catch (ex) {
          if (typeof console !== 'undefined' && typeof console.error === 'function') {  // eslint-disable-line no-console
            console.error('[Styleguide/StyleguideAtellier] Failed to remove invalidComponents from localStorage.', ex);  // eslint-disable-line no-console
          }
        }

        return (
          <ReactAtellier
            components={styleguides.filter(({ component }) => (!!component)).map(({
              component,
              componentPath,
            }) => {
              const componentDisplayName = getReactComponentDisplayName(component);

              // Append component path if it differs from the exported component name, for clarity. -- sompylasar
              const componentName = (
                componentPath !== componentDisplayName
                  ? componentDisplayName + ' from /' + componentPath + ''
                  : componentDisplayName
              );

              return {
                component,
                componentName,
              };
            })}
          />
        );
      }}
    </BrowserOnlyRender>
  );
};

export default StyleguideAtellier;
```

**Comment by sapegin** [comment] 2016-09-21 20:14
@sompylasar Thanks! For me it looks too complicated ;-)

**Comment by sompylasar** [comment] 2016-09-21 20:27
@sapegin What I've shown is written once to dynamically provide the component playground with all the components. What I wanted to achieve  is to have styleguide descriptors next to the components' code in the file structure. Unfortunately, webpack cannot do dynamic context-wise requires, so I have to hardcode certain paths which is not nice and prevents from moving this code into the styleguide library so that it can be imported. The component search function is also reused at a separate page that renders complex usecases of each component via `render` functions (both `render` and `component` are defined next to the component code; `component` is rendered at the atellier stage).

**Closed** 2016-09-28 14:25 UTC
Labels: enhancement, help wanted
